name: pipeline

on: [push]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "18"
      - run: corepack enable
      - run: yarn install
      - run: yarn sort --check
      - run: yarn format
      - run: yarn lint
      - run: yarn test
  release:
    runs-on: ubuntu-latest
    needs: check
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "18"
      - run: corepack enable
      - run: yarn install
      - run: yarn package
      - run: yarn vsce package --no-yarn
      - run: echo "VERSION=$(node -p "require('./package.json').version")" >> "$GITHUB_ENV"
      - run: gh release create v$VERSION --generate-notes swap-tsconfig-$VERSION.vsix
        env:
          GH_TOKEN: ${{ github.token }}
      - run: yarn vsce publish --no-yarn
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
